import sqlite3
cno=sqlite3.connect('asim1.db')
print("!!  Database Created Successfully  !!")
cno.execute('''create table employee(code varchar not null,name varchar not null,salary number null);''')
print("!!  Table Created Successfully  !!")
cno.execute("insert into employee(code,name,salary) values('S1','Asim',100)")
cno.execute("insert into employee(code,name,salary) values('S2','Hina',101)")
cno.execute("insert into employee(code,name,salary) values('S3','Yahiya',102)")
cno.execute("insert into employee(code,name,salary) values('S4','Zishan',103)")
print("!!   Data Inserted   !!")
cno.commit()
crs=cno.execute("select * from employee")
print("--------------------------------------")
print("!! Original Data !!\n")
print("--------------------------------------")
for rs in crs:
    print("Employee Id:",rs[0])
    print("Employee Name:",rs[1])
    print("Employee Salary:",rs[2],"\n")
cno.execute("delete from employee WHERE code = 'S3'")
cno.execute("delete from employee WHERE code = 'S4'")
cno.execute("update employee set name = 'Asim Sarkar' where code = 'S1'")
cno.execute("update employee set name = 'Hina Sarkar' where code = 'S2'")
print("--------------------------------------")
print("!! After Updation !! \n")
print("--------------------------------------")
crs=cno.execute("select * from employee")
for rs in crs:
    print("Employee Id:",rs[0])
    print("Employee Name:",rs[1])
    print("Employee Salary:",rs[2],"\n")