tup = (1,2,3,4,5,6,7,8,"Asim","Hina")
print("Tuple:",tup)
print(8 in tup)
print(len(tup))#Length
print(tup[8],tup[9])#Index(+)
print(tup[-1],tup[-2])#Index(-)
print(tup.index("Asim"))
print(tup.count(5))
print("     S L I C I N G       ")
print("Reverse:",tup[::-1])
print(tup[1:6])
print(tup[:5])
print(tup[1::8])